<?php
mysql_connect('localhost', 'root', '') or die();
mysql_select_db('major');


$string =">9RNT:A|PDBID|CHAIN|SEQUENCE
ACDYTCGSNCYSSSDVSTAQAAGYKLHEDGETVGSNSYPHKYNNYEGFDFSVSSPYYEWPILSSGDVYSGGSPGADRVVFNENNQLAGVITHTGASGNNFVECT*
--BBBB--BBB-HHHHHHHHHHHHHHHHH----CCCCBBBBB-------------BBBBB----BBB-------BBBBBBBBBB-BBBBBBB--BBBB-BBB--*

>9RAT:A|PDBID|CHAIN|SEQUENCE
KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMSITDCRETGSSKYPNCAYKTTQANKHIIVACEGNPYVPVHFDASV*
---HHHHHHHHH----BBB--HHHHHHHHHHH--BBBBB--BBBBBB---HHHHHHHHHBBBB--BBB---BBB-BBBBBBBBBBB-----BBB--BBBBBBBB-BBBBBBCCCCBBBBBBBB-*

>4UBP:A|PDBID|CHAIN|SEQUENCE
MHLNPAEKEKLQIFLASELLLRRKARGLKLNYPEAVAIITSFIMEGARDGKTVAMLMEEGKHVLTRDDVMEGVPEMIDDIQAEATFPDGTKLVTVHNPIS*
----HHHHHHHHHHHHHHHHHHHHH------HHHHHHHHHHHHHHHHHH---HHHHHHHHHH---HHH----HHHH-BBBBBBBBB--BBBBBBBBB---*

>4UBP:B|PDBID|CHAIN|SEQUENCE
MSNNNYIVPGEYRVAEGEIEINAGREKTTIRVSNTGDRPIQVGSHIHFVEVNKELLFDRAEGIGRRLNIPSGTAARFEPGEEMEVELTELGGNREVFGISDLTNGSVDNKELILQRAKELGYKGVE*
---------------BBBBBCCCC--BBBBBBBB-BBB-BBBB----HHH----BBB-HHHH--BBB------BBBB----BBBBBBBB--------------BBB---HHHHHHHHHHH------*

>3GRS:A|PDBID|CHAIN|SEQUENCE
ACRQEPQPQGPPPAAGAVASYDYLVIGGGSGGLASARRAAELGARAAVVESHKLGGTCVNVGCVPKKVMWNTAVHSEFMHDHADYGFPSCEGKFNWRVIKEKRDAYVSRLNAIYQNNLTKSHIEIIRGHAAFTSDPKPTIEVSGKKYTAPHILIATGGMPSTPHESQIPGASLGITSDGFFQLEELPGRSVIVGAGYIAVEMAGILSALGSKTSLMIRHDKVLRSFDSMISTNCTEELENAGVEVLKFSQVKEVKKTLSGLEVSMVTAVPGRLPVMTMIPDVDCLLWAIGRVPNTKDLSLNKLGIQTDDKGHIIVDEFQNTNVKGIYAVGDVCGKALLTPVAIAAGRKLAHRLFEYKEDSKLDYNNIPTVVFSHPPIGTVGLTEDEAIHKYGIENVKTYSTSFTPMYHAVTKRKTKCVMKMVCANKEEKVVGIHMQGLGCDEMLQGFAVAVKMGATKADFDNTVAIHPTSSEELVTLR*
-----------------BBB-BBBBB---HHHHHHHHHHHH----BBBBBBB---HHHHHHHHHHHHHHHHHHHHHHHHCCCCCCC---------HHHHHHHHHHHHHHHHHHHHHHHHH---BBBBBB-BBB-----BBB---BBBB---BBB---BBB----CCC---HHH---HHHH-------BBBBBB---HHHHHHHHHHHH---BBBBB-BBBBB-----HHHHHHHHHHHHH---BBB--BBBBBBBB-BBBBBBBBBB-------BBBBBBBBBBBBB---BBBB-CCCCHHHH----------------------BBB-HHHH-----HHHHHHHHHHHHHHHH--------------BBB-BBB-BBBBB--HHHHHHHH-HHHBBBBBBBB--HHHHH------BBBBBBBBCCCCBBBBBBBBB--HHHHHHHHHHHHH----HHHHH-----BBBBHHHHH---*

>3ER7:A|PDBID|CHAIN|SEQUENCE
MMNTTTLDRYFDLFDASRTDEKAFDDLISLFSDEITFVLNGQEQHGIDAWKQFVRMVFTANQDIKHMYAGWVPSETGDTMETRWAVCGKSADGSVFTQDGTDIARLNADGKIVYLANVPDDTAMFNQYND*
-----HHHHHHHHHHH----HHHHHHHHH-BBBBBBBBB--BBBB-HHHHHHHHHHHHHHBBBBBBBB---BB------BBBBBBBBBBB----BBBBBBBBBBBB-----BBBBBBBB-----------*

>3EF8:A|PDBID|CHAIN|SEQUENCE
MTDTNLVEMRAIERMMFDYSYHLDMNHPEELAALFVEDCEVSYAPNFGATGRDAYKKTLEGIGTFFRGTSHHNSNICIDFVSETEANVRSVVLAIHRYTKERPDGILYGQYFDTVVKVDGQWKFKRRELRTTMTTDYHVRAANPIGRAE*
-HHHHHHHHHHHHHHHHHHHHHHH---HHHHH--BBBBBBBBBB--BBBB-HHHHHHH---HHHHBBBBBBBBBBBBBBBBB--BBBBBBBBBBBBBB------BBBBBBBBBBBBBB--BBBBBBBBBBBBBBB--------------*

>3BY4:A|PDBID|CHAIN|SEQUENCE
KRVLKSTEMSIGGSGENVLSVHPVLDDNSCLFHAIAYGIFKQDSVRDLREMVSKEVLNNPVKFNDAILDKPNKDYAQWILKMESWGGAIEIGIISDALAVAIYVVDIDAVKIEKFNEDKFDNYILILFNGIHYDSLTMNEFKTVFNKNQPESDDVLTAALQLASNLKQTGYSFNTHKAQIKCNTCQMTFVGEREVARHAESTGHVDFGQNR*
-------BBBBCCC--BBBBBB-------HHHHHHHHHHH-----HHHHHHHHHHHHH-CCCC-HHHH---HHHHHHH---------HHHHHHHHHHH--BBBBBBCCCCBBBBBBCCC-BBBBBBBB----BBBBBBCCC----------HHHHHHHHHHHHHHHHH-------------------------------------------*

>3BQC:A|PDBID|CHAIN|SEQUENCE
MSGPVPSRARVYTDVNTHRPREYWDYESHVVEWGNQDDYQLVRKLGRGKYSEVFEAINITNNEKVVVKILKPVKKKKIKREIKILENLRGGPNIITLADIVKDPVSRTPALVFEHVNNTDFKQLYQTLTDYDIRFYMYEILKALDYCHSMGIMHRDVKPHNVMIDHEHRKLRLIDWGLAEFYHPGQEYNVRVASRYFKGPELLVDYQMYDYSLDMWSLGCMLASMIFRKEPFFHGHDNYDQLVRIAKVLGTEDLYDYIDKYNIELDPRFNDILGRHSRKRWERFVHSENQHLVSPEALDFLDKLLRYDHQSRLTAREAMEHPYFYTVVKDQARMG*
---------BBBCCCCCC--HHHH-HHH-------HHHBBBBBBBBB-BBBBBBBBBBCCC--BBBBBBB----HHHHHHHHHHHHHH--------BBBBBB-CCC--BBBBBB------HHHHHHH--HHHHHHHHHHHHHHHHHHHH---------HHHBBBBCCCCBBBB--HHH----------------HHH--HHHH--------HHHHHHHHHHHHHHHH--BBBB----HHHHHHHHHHHH-HHHHHHHHHH--------HHHHH-------HHHH--CCCHHH--HHHHHHHH------HHH---HHHHH--HHH--HHH---BBB*

>2RBS:A|PDBID|CHAIN|SEQUENCE
MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNCNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRCAAINQVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYK*
--HHHHHHHHH--BBBBBB-BBB-BBBB--BBB-BBB-HHHHHHHHHHHH----BBB----HHH---HHHHHHHHHHHH--CCCHHHHHH--HHHHHHHHHHHHHH-HHHHH--HHHHHHHHCCCHHHHHHHH---HHHHH-HHHHHHHHHHHHHBBBCCCH*

>2RH7:A|PDBID|CHAIN|SEQUENCE
MDLAKLGLKEVMPTKINLEGLVGDHAFSMEGVGEGNILEGTQEVKISVTKGAPLPFAFDIVSVAFGYGNRAYTGYPEEISDYFLQSFPEGFTYERNIRYQDGGTAIVKSDISLEDGKFIVNVDFKAKDLRRMGPVMQQDIVGMQPSYESMYTNVTSVIGECIIAFKLQTGKHFTYHMRTVYKSKKPVETMPLYHFIQHRLVKTNVDTASGYVVQHETAIAAHSTIKKIEGSLP*
----------BBBBBBBBBBBB--BBBBBBBBBBBB----BBBBBBBBBB-------HHHH--------------------HHHHH----BBBBBBBBB----BBBBBBBBBBB--BBBBBBBBBBB------HHHH--BBBB--BBBBBBBB--BBBBBBBBBBBB----BBBBBBBBBBBB----------BBBBBBBBBBB-------BBBBBBBBBB------------*

>2SRC:A|PDBID|CHAIN|SEQUENCE
VTTFVALYDYESRTETDLSFKKGERLQIVNNTEGDWWLAHSLSTGQTGYIPSNYVAPSDSIQAEEWYFGKITRRESERLLLNAENPRGTFLVRESETTKGAYCLSVSDFDNAKGLNVKHYKIRKLDSGGFYITSRTQFNSLQQLVAYYSKHADGLCHRLTTVCPTSKPQTQGLAKDAWEIPRESLRLEVKLGQGCFGEVWMGTWNGTTRVAIKTLKPGTMSPEAFLQEAQVMKKLRHEKLVQLYAVVSEEPIYIVTEYMSKGSLLDFLKGETGKYLRLPQLVDMAAQIASGMAYVERMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQGAKFPIKWTAPEAALYGRFTIKSDVWSFGILLTELTTKGRVPYPGMVNREVLDQVERGYRMPCPPECPESLHDLMCQCWRKEPEERPTFEYLQAFLEDYFTSTEPQYQPGENL*
-BBBBBBB-----BBBB-------BBBBB---BBBBBBBBBCCC--BBBBBHHHBBB---HHH---BBB---HHHHHHHH-BBBB---BBBBBB-BBB---BBBBBBBBBCCCBBBBBBBBBBB-BBB-BBBB--BBBBBHHHHHHHH------BBB-------------BBBB-------HHHBBBBBBBBB----BBBBBBBCCCBBBBBBB--CCC--HHHHHHHHHHHHH--------BBBBB-BBB-BBBB-------HHHHH-HHHH----HHHHHHHHHHHHHHHHHHHH---------HHHBBB-HHH-BBB----HHHH---HHHH--CCCC--HHH--HHHHHH----HHHHHHHHHHHHHHHHCCC--------HHHHHHHHH------------HHHHHHHHHH----HHH---HHHHHHHHHCCC-------------*

>2V3Z:A|PDBID|CHAIN|SEQUENCE
MSEISRQEFQRRRQALVEQMQPGSAALIFAAPEVTRSADSEYPYRQNSDFWYFTGFNEPEAVLVLIKSDDTHNHSVLFNRVRDLTAEIWFGRRLGQDAAPEKLGVDRALAFSEINQQLYQLLNGLDVVYHAQGEYAYADVIVNSALEKLRKGSRQNLTAPATMIDWRPVVHEMRLFKSPEEIAVLRRAGEITAMAHTRAMEKCRPGMFEYHLEGEIHHEFNRHGARYPSYNTIVGSGENGCILHYTENECEMRDGDLVLIDAGCEYKGYAGDITRTFPVNGKFTQAQREIYDIVLESLETSLRLYRPGTSILEVTGEVVRIMVSGLVKLGILKGDVDELIAQNAHRPFFMHGLSHWLGLDVHDVGVYGQDRSRILEPGMVLTVAPGLYIAPDAEVPEQYRGIGIRIEDDIVITETGNENLTASVVKKPEEIEALMVAARKQ*
-----HHHHHHHHHHHHHH--BBBBBBBB-----BBB----------HHHHHHH-------BBBBBB-BBB-BBBBBBB----HHHHHHH----HHHHHHHHH--BBBBBHHHHHHHHHHHH---BBBB------HHHHHHHHHHHHHHH--HHH-----BBBB--HHHHHHHHH---HHHHHHHHHHHHHHHHHHHHHHHH------HHHHHHHHHHHHHH----BBBB--BBBBHHHHH---------------BBBBBB-BBB------BBBBBB------HHHHHHHHHHHHHHHHHHHH------HHHHHHHHHHHHHHHHHH-------HHHHHHCCCCCCC---------BBBBB------HHH--------BBBB--BBB--------HHH--BBBB-BBBBBBB--BBBBBB------HHHHHHHHHHHH--*

>2V6A:H|PDBID|CHAIN|SEQUENCE
MVPQTETKAGAGFKAGVKDYRLTYYTPDYVVRDTDILAAFRMTPQPGVPPEECGAAVAAESSTGTWTTVWTDGLTSLDRYKGRCYDIEPVPGEDNQYIAYVAYPIDLFEEGSVTNMFTSIVGNVFGFKALRALRLEDLRIPPAYVKTFVGPPHGIQVERDKLNKYGRGLLGCTIKPKLGLSAKNYGRAVYECLRGGLDFTKDDENVNSQPFMRWRDRFLFVAEAIYKAQAETGEVKGHYLNATAGTCEEMMKRAVCAKELGVPIIMHDYLTGGFTANTSLAIYCRDNGLLLHIHRAMHAVIDRQRNHGIHFRVLAKALRMSGGDHLHSGTAVGKLEGEREVTLSFVDLMRDDYVEKDRSRGIYFTQDWCSMPGVMPVASGGIHVWHMPALVEIFGDDACLQFGGGTLGHPWGNAPGAAANRVALEACTQARNEGRDLAREGGDVIRSACKWSPELAAACEVWKEIKFEFDTIDKL*
--------------------HHHH-----------BBBBBBBBB-----HHHHHHHHHHHCCC--BBB-HHHHH--HHHH--BBBBBBB---BBB-BBBBBBB-HHH-----HHHHHHHHH--HHH---BBBBBBBBBB--HHHH---------HHHHHHHH------BBB---BBBB---HHHHHHHHHHHHH---BBBB-----BBB----HHHHHHHHHHHHHHHHHHH----BBBBB-----HHHHHHHHHHHHHH--BBBBBBHHHH-HHHHHHHHHHHHHH--BBBBB---HHHHH--BBBBB-HHHHHHHHHHH--BBBB---BBBBB---HHHHHHHHHHHH-BBB---HHH--------------BBBBBBB--HHHHHHHHHHH-BBBBBB--HHHH-----HHHHHHHHHHHHHHHHHHHH----HHHHHHHHHHHHHHH-HHHHHHHHHH-------------*

>2V6A:I|PDBID|CHAIN|SEQUENCE
MMVWTPVNNKMFETFSYLPPLTDEQIAAQVDYIVANGWIPCLEFAEADKAYVSNESAIRFGSVSCLYYDNRYWTMWKLPMFGCRDPMQVLREIVACTKAFPDAYVRLVAFDNQKQVQIMGFLVQRPKTARDFQPANKRSV*
-------------CCCC-----HHHHHHHHHHHHH---BBBBBBB-HHH-----HHHHH---------BBB--BBBB--------HHHHHHHHHHHHHH---BBBBBBBBBCCCBBBBBBBBB----------HHH----*

>2CYZ:B|PDBID|CHAIN|SEQUENCE
MDGVHDLAGVQGFGKVPHTVNADIGPTFHAEWEHLPYSLMFAGVAELGAFSVDEVRYVVERMEPRHYMMTPYYERYVIGVATLMVEKGILTQDELESLAGGPFPLSRPSESEGRPAPVETTTFEVGQRVRVRDEYVPGHIRMPAYCRGRVGTISHRTTEKWPFPDAIGHGRNDAGEEPTYHVKFAAEELFGSDTDGGSVVVDLFEGYLEPAA*
------------------------------CCCCHHHHHHHHHHH------HHHHHHHHH---HHHHHH--HHHHHHHHHHHHHHH-----HHHHHHHH----------------------------BBBB------------HHH---BBBBBBB-------HHHHCCC--------BBBBBBBHHHHH------BBBBBBBBHHHBBB--*

>2ZDP:A|PDBID|CHAIN|SEQUENCE
MFMAENRLQLQKGSAEETIERFYNRQGIETIEGFQQMFVTKTLNTEDTDEVKILTIWESEDSFNNWLNSDVFKEAHKNVRLKSDDDGQQSPILSNKVFKYDIGYHYQK*
-BBBBBBBBB----HHHHHHHHH----HHH---BBBBBBBBB----BBBBBBBBBBBB-HHHHHHHH--HHHHHCCC--------------BBBBBBBBBBBBBBBB-*

>2ZGW:A|PDBID|CHAIN|SEQUENCE
MLGLKTSIIGRRVIYFQEITSTNEFAKTSYLEEGTVIVADKQTMGHGALNRKWESPEGGLWLSIVLSPKVPQKDLPKIVFLGAVGVVETLKEFSIDGRIKWPNDVLVNYKAIAGVLVEGKGDKIVLGIGLNVNNKVPNGATSMKLELGSEVPLLSVFRSLITNLDRLYLNFLKNPMDILNLVRDNMILGVRVKILGDGSFEGIAEDIDDFGRLIIRLDSGEVKKVIYGDVSLRFL*
-----------BBBBB-----HHHHHHH-------BBBB--------HHH---------BBBBBBB-----HHHHHHHHHHHHHHHHHHHHH-----BBB---BBBB--BBBBBBBBBBB--BBBBBBBB------------HHHHH-----HHHHHHHHHHHHHHHHHHHHH---HHHHHHHH------BBBBB----BBBBBBBB-----BBBB-----BBBB-----BBBB-*

>2ZJD:A|PDBID|CHAIN|SEQUENCE
MPSEKTFKQRRTFEQRVEDVRLIREQHPTKIPVIIERYKGEKQLPVLDKTKFLVPDHVNMSELIKIIRRRLQLNANQAFFLLVNGHSMVSVSTPISEVYESEKDEDGFLYMVYASQETFGMKLSV*
------HHHH--HHHHHHHHHHHHHH---BBBBBBB-----BBB------BBBBB----HHHHHHHHHHHH---CCC-BBBBBCCC--CCC---HHHHHHHH------BBBBBBBHHHHHH----*

>3B72:A|PDBID|CHAIN|SEQUENCE
MRSLLILVLCFLPLAALGKVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL*
----------------------HHHHHHHHHHCCCCCHHH--HHHHHHHHHHHHBBB---BBB-BBB-BBBCCCC--CCCC---BBB----------HHHHHBBB-HHHHHHHHHHHHBBB-HHH-HHHHHHCCC--HHHHCCC---*

>3BKT:A|PDBID|CHAIN|SEQUENCE
HGTQGFAVLSYVYEHEKRDLASRIVSTQHHHHDLSVATLHVHINHDDCLEIAVLKGDMGDVQHFADDVIAQRGVRHGHLQCLPKED*
BBBBBBBBBBBBBB---HHHHHHHHHHHHH-HHHBBBBBBBB-BBBBBBBBBBBBBBHHHHHHHHHHHH-BBB-BBBBBBBBB---*

>2IMH:A|PDBID|CHAIN|SEQUENCE
MSLTFSILAHDPETGAIGGAAATGSLCVGGWVLRGDLNAGMSASQGAAPSTFWGEEVLQHLRDGSHPEDAVNHVTSQDSGRAYRQLAAMDLLGNAAAFTGSENQDIKGSVTFASGIASGNMLGDNSVLGAMTEAFVASDLTFERRLLAALIAAEGAGSDFRGLLSAAMLVLHPDRPPVTLRIDYHPDNPIGALEQLYQKATTGDYADWARQVPVLSDKERILDEG*
-BBBBBBBB----BBBBBBBB----HHHHHBBBB---BBBBBB-----HHHHHHHHHHHH----HHHHHHHHHH----HHH-BBBBBB----BBBBB--------BBBBB--BBBBBB-----HHHHHHHHHHHH----HHHHHHHHHHHHHH---------BBBBBBBB--BBBBBBBB------HHHHHHHHHHHH--HHHHHHH------------------*

>2IMJ:A|PDBID|CHAIN|SEQUENCE
MSSNAQVRPPLPPFTRESAIEKIRLAEDGWNSRDPERVSLAYTLDTQWRNRAEFAHNREEAKAFLTRKWAKELDYRLIKELWAFTDNRIAVRYAYEWHDDSGNWFRSYGNENWEFDEQGLMARRFACINDMPIKAQERKFHWPLGRRPDDHPGLSELGL*
---------------HHHHHHHHHHHHHHH----HHHHH--BBBBBBBBB--BBB--HHHHHHHHHHHHHH-BBBBBBBBBBBBB--BBBBBBBBBBB-----BBBBBBBBBBBB-----BBBBBBBBBBBBB-HHH----------------HHHH--*

>2INW:A|PDBID|CHAIN|SEQUENCE
MSDTLPGTTPPDDNHDRPWWGLPCTVTPCFGARLVQEGNRLHYLADRAGIRGRFSDVDAYHLDQAFPLLMKQLELMLTGGELNPRHQHTVTLYAKGLTCEADTLGSCGYVYLAVYPTPAAPATTVLE*
----------------------------BBBBBBBBB--BBB--HHHBBBB----HHHHHHHHHHHHHHHHHHHHHHHH----------BBBBB--BBBBBB------BBBBBBBB-----------*

>2INX:A|PDBID|CHAIN|SEQUENCE
MNLPTAQEVQGLMARYIELVDVGDIEAIVQMYADDATVENPFGQPPIHGREQIAAFYRQGLGGGKVRACLTGPVRASHNGCGAMPFRVEMVWNGQPCALDVIDVMRFDEHGRIQTMQAYWSEVNLSVREPQ*
-----HHHHHHHHHHHHHHHHH--HHHHHHHBBBBBBBBBB-------HHHHHHHHHHHHHBBB--BBBBBB-----BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB-----BBBBBBB--HHHBBB----*

>2IPR:A|PDBID|CHAIN|SEQUENCE
KVEDPKDFPSELLSFLSHAVFSNRTLACFAIYTTKEKAALLYKKIMEKYSVTFISRHNSYNHNILFFLTPHRHRVSAINNYAQKLCTFSFLICKGVNKEYLMYSALTRDPFSVIEESLPGGLKEHDFNP*
---------HHHHHH----------BBBBBBBB-HHHHHHHHHHHHHHH---BBBBBBB--BBBBBBBBBBBB-HHHHHHHHH-------BBBBB---HHHHHHHH-----BBBBB-------HHH---*

>2IWX:A|PDBID|CHAIN|SEQUENCE
MASETFEFQAEITQLMSLIINTVYSNKEIFLRELISNASDALDKIRYKSLSDPKQLETEPDLFIRITPKPEQKVLEIRDSGIGMTKAELINNLGTIAKSGTKAFMEALSAGADVSMIGQFGVGFYSLFLVADRVQVISKSNDDEQYIWESNAGGSFTVTLDEVNERIGRGTILRLFLKDDQLEYLEEKRIKEVIKRHSEFVAYPIQLVVTKEVE*
---BBBB--HHHHHHHHHHHH----HHHHHHHHHHHHHHHHHHHHHHHCCC-HHHH-------BBBBBBHHH-BBBBBB------HHHHHHHH-CCC---HHHHHHHHHH---HHHHHHH--HHHHHHH-BBBBBBBBB------BBBBB-BBBBBBBBB-BBB---BBBBBBBBBB----HHHH-HHHHHHHHHHH--BBBB-BBB-------*

>2NML:A|PDBID|CHAIN|SEQUENCE
MSHTILLVQPTKRPEGRTYADYESVNECMEGVCKMYEEHLKRMNPNSPSITYDISQLFDFIDDLADLSCLVYRADTQTYQPYNKDWIKEKIYVLLRRQAQQAGK*
---BBBBB-----HHH-BBBBBBBHHHHHHHHHHHHHHHHHHH----------HHHHHHHHHHBBBBBBBBBBCCCCBBBBB-HHHHHHHHHHHHHHHHH----*

>2OPL:A|PDBID|CHAIN|SEQUENCE
MSQTTVVNGVNVDQLMATIEQIKAKPEIAQFKFRATNQWMGGTHNQATIKDFYGACAEDDTRKPMVFDLDEPPVLLGENRGANPVEYLLVALSGCLTTSLVAHAAARGIALRGVKSRYEGDIDLRGFLGLSEEVPVGYREIRVFFSIDADLTDGQKEELIRMAQKYSPVYNTVAKPVPVAVLLDRG*
-----BB--BBHHHHHHHHHHHHH-HHHHBBBBBBBBBBBB--BBBBBB--BBB--BBB-----BBBBB---HHH--------HHHHHHHHHHHHHHHHHHHHHHH------BBBBBBBBBBB----------------BBBBBBBBB----HHHHHHHHHHHHHH-HHHHHHH----BBBBB---*

>2OU9:A|PDBID|CHAIN|SEQUENCE
MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFCNSLAMLQQKRWDEAAVNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL*
--HHHHHHHHH--BBBBBB-BBB-BBBB--BBB-BBB-HHHHHHHHHHHH----BBB----HHH---HHHHHHHHHHHH--CCCHHHHHH--HHHHHHHHHHHHHH-HHHHH--HHHHHHHHCCCHHHHHHHH---HHHHH-HHHHHHHHHHHHHBBBCCCHHH*

>2OY2:A|PDBID|CHAIN|SEQUENCE
NPKWERTNLTYRIRNYTPQLSEAEVERAIKDAFELWSVASPLIFTRISQGEADINIAFYQRDHGDNSPFDGPNGILAHAFQPGQGIGGDAHFDAEETWTNTSANYNLFLVAAHEFGHSLGLAHSSDPGALMYPNYAFRETSNYSLPQDDIDGIQAIYG*
--BBB-BBBBBBB----BBB-HHHHHHHHHHHHHHHH-----BBBB-BBB--BBBBBBB----BBB----BBBB--BBB--BBBCCCC-BBBB-----BBBBBB--HHHHHHHHHHHHH------------BBB-----BBB----HHHHHHHHHHH-*

>2PBD:A|PDBID|CHAIN|SEQUENCE
MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYVGDEAQSKRGILTLKYPIEHGIITNWDDMEKIWHHTFYNELRVAPEEHPTLLTEAPLNPKANREKMTQIMFETFNVPAMYVAIQAVLSLYASGRTTGIVLDSGDGVTHNVPIYEGYALPHAIMRLDLAGRDLTDYLMKILTERGYSFVTTAEREIVRDIKEKLCYVALDFENEMATAASSSSLEKSYELPDGQVITIGNERFRCPETLFQPSFIGMESAGIHETTYNSIMKCDIDIRKDLYANNVMSGGTTMYPGIADRMQKEITALAPSTMKIKIIAPPERKYSVWIGGSILASLSTFQQMWITKQEYDEAGPSIVHRKCF*
---CCCCC-BBBBB-BBBBBBBB--BBB-BBBBB--BBBB-CCC---BBB---BBBHHHHHHH--BBBBB-BBB------HHHHHHHHHHHHHCCC---HHH--BBBBB-----HHHHHHHHHHHHH----BBBBBBBHHHHHHHH---BBBBBBBBBBB-BBBBBBB-----HHH-BBBB--HHHHHHHHHHHHHHH------HHHHHHHHHHHHHH------HHHHHHHHHH-BBB-BBBB-BBB-BBBBB-HHHHHHHCCC-HHHH------HHHHHHHHHH---HHHHHHHH--BBBBBHHH-BBBHHHHHHHHHHHH-HHH--------CCCC-HHHHHHHHHHH-HHHHHHBBBHHHHHHH-HHHH-----*

>2PBD:P|PDBID|CHAIN|SEQUENCE
AGWNAYIDNLMADGTCQDAAIVGYKDSPSVWAAVPGKTFVNITPAEVGVLVGKDRSSFYVNGLTLGGQKCSVIRDSLLQDGEFSMDLRTKSTGGAPTFNVTVTKTDKTLVLLMGKEGVHGGLINKKCYEMASHLRRSQY*
----HHHHHHHH-BBBBBBBBBBBBBBB-BBBB------HHH--HHHHHHHH-----HHH---BBB--BBBBBBBBBBBBCCC-BBBBBB--BBBB---BBBBBB-BBBBBBBBB-----HHHHHHHHHHHHHHHHH--*

>2HVF:A|PDBID|CHAIN|SEQUENCE
MKVIFLKDVKGKGKKGEIKNVADGYANNFLFKQALAIEATPANLKALEAQKQ*
-BBBBBB--CCCHHH--BBB--HHHHHHCCCCCCBBBB--HHHHHHHHHHH-*

>2HX0:A|PDBID|CHAIN|SEQUENCE
MTVSHHNASTARFYALRLLPGQEVFSQLHAFVQQNQLRAAWIAGCTGSLTDVALRYAGQEATTSLTGTFEVISLNGTLELTGEHLHLAVSDPYGVMLGGHMMPGCTVRTTLELVIGELPALTFSRQPCAISGYDELHISSR*
-----------BBBBBBB-----HHHHHHHHHHHH----BBBBBBBBBBBBBBBB-------BBBBBBBBBBBBBBBBB--BBBBBBBBB-----BBBBBB----BBBBBBBBBBBB---BBBBBBB------BBBBBBB-*

>2HX5:A|PDBID|CHAIN|SEQUENCE
MNPENWLLLRRVVRFGDTDAAGVMHFHQLFRWCHESWEESLESYGLNPADIFPGSRKSEVTPEVALPIIHCQADFRRPIHTGDALAMELRPERLNPNSFQVHFEFRCEEQIAAHALIRHLAINAQTRHRCALPEGIDRWLEASGVGKIGSI*
---HHHHBBBBB--HHH----BBB---HHHHHHHHHHHHHHHHH---HHHH-----------BBB--BBBBBBBB--------BBBBBBBBBBBB--BBBBBBBBBB--BBBBBBBBBBB---CCC-------HHHHHHHHH---------*

>2I8E:A|PDBID|CHAIN|SEQUENCE
MAMLYLIFYDITDDNLRNRVAEFLKKKGLDRIQYSVFMGDLNSSRLKDVEAGLKIIGNRKKLQEDERFFILIVPITENQFRERIVIGYSGSEREEKSNVVW*
--BBBBBBBBB--HHHHHHHHHHHHH---BBBB--BBBBBB-HHHHHHHHHHHHHH-----------BBBBBBBB-HHHHH--------------------*

>2IA1:A|PDBID|CHAIN|SEQUENCE
MEKQIESYYQEIAQLIIDMIPEEWAEVRFYAQEDHDGWKIFFFHYLSASSDEWTKDIDIRDVIKVPQDEFMEKYNELSFCISDFRKDYAEAFGEPWMSFQMTFYASGKFNIDFYYDKNPFDTFLTRLAWQYEHFGTIPEDSFYKETLNEYLEEKAQGKRYPFLEPLKEE*
HHHHHHHHHHHHHHHHHHH----BBBBBBBBBB-----BBBBBBBBB-----BBBHHHHHH-----HHHHHHHHHHHHHHHHHHHHHHHHHH-----BBBBBBB----BBBBBB-------HHHHHHHHHHHHH------HHHHHHHHHHHHHH------HHH------*

>2HHN:A|PDBID|CHAIN|SEQUENCE
NRILPDSVDWREKGCVTEVKYQGSCGACWAFSAVGALEAQLKLKTGKLVSLSAQNLVDCSTEKYGNKGCNGGFMTTAFQYIIDNKGIDSDASYPYKAMDQKCQYDSKYRAATCSKYTELPYGREDVLKEAVANKGPVSVGVDARHPSFFLYRSGVYYEPSCTQNVNHGVLVVGYGDLNGKEYWLVKNSWGHNFGEEGYIRMARNKGNHCGIASFPSYPEI*
-----------HHHH----------BBB-HHHHHHHHHHHHHHHHHH-------HHHHHHH--HHH---HHH---HHHHHHHHHHH--BBBCCC-------------HHHBBB---BBBB-----HHHHHHHHHH---BBBBB----HHHHH--BBBB----------BBBBBBBBBBB--BBBBBBB---CCC-----BBBBB-BBBBHHHCCC--BBB*

>2HJL:A|PDBID|CHAIN|SEQUENCE
GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRMAPRAPWIEQEGPEYWDGETRNMKASAQTYRENLRIALRYYNQSEAGSHIIQVMYGCDVGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQIIQRKWEAARVAEQLRAYLEGLCVEWLRRYLENGKETLQRADPPKTHVTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRW*
--BBBBBBBBBB----BBB-BBBBBBBB--BBBBBBB--BBB-------HHH----HHHHHHHHHHHHHHHHHHHHHHHHHHHH---------BBBBBBBBBB-----BBBBBBBBBB--BBBBBB------BBBBBHHHHHHHHHHHH--HHHHHHHHHH-HHHHHHHHHHHH-HHHH------BBBBBBBBBB--BBBBBBBBBBBBBB--BBBBBB-----HHHHH-------BBB-BBBBBBBBBB---HHHBBBBBB---BBB-BBB--*

>2HJL:B|PDBID|CHAIN|SEQUENCE
IQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM*
-----BBBBBBBB-HHH---BBBBBBBBBBBBB--BBBBBB--BBB----BBBBBBBBBBBB---BBBBB-------BBBBBB---BBB-BBBB--HHH*

>2A94:A|PDBID|CHAIN|SEQUENCE
APKAKIVLVGSGMIGGVMATLIVQKNLGDVVLFDIVKNMPHGKALDTSHTNVMAYSNCKVSGSNTYDDLAGADVVIVTAGFTKAPGKSDKEWNRDDLLPLNNKIMIEIGGHIKKNCPNAFIIVVTNPVDVMVQLLHQHSGVPKNKIIGLGGVLDTSRLKYYISQKLNVCPRDVNAHIVGAHGNKMVLLKRYITVGGIPLQEFINNKLISDAELEAIFDRTVNTALEIVNLHASPYVAPAAAIIEMAESYLKDLKKVLICSTLLEGQYGHSDIFGGTPVVLGANGVEQVIELQLNSEEKAKFDEAIAETKRMKALA*
-----BBBBB---HHHHHHHHHHHH----BBBBB-BBBBHHHHHHHHHH-HHHHH-----BBBB--HHHH---BBBB------------HHH--HHHHHHHHHHHHHHHHHHHHHH---BBBBB-BBBHHHHHHHHHHHH---HHHBBB--HHHHHHHHHHHHHHHH---HHH----BBB---------HHH-------HHHHHH-----HHHHHHHHHHHH-HHHHHHHHBBB--HHHHHHHHHHHHHHH----BBBBBBBBBBBHHH-BBBBBBBBBBBB--BBBBB------HHHHHHHHHHHHHHHHHHHH*

>2HQS:A|PDBID|CHAIN|SEQUENCE
RIVIDSGVDSGRPIGVVPFQWAGPGAAPEDIGGIVAADLRNSGKFNPLDRARLPQQPGSAQEVQPAAWSALGIDAVVVGQVTPNPDGSYNVAYQLVDTGGAPGTVLAQNSYKVNKQWLRYAGHTASDEVFEKLTGIKGAFRTRIAYVVQTNGGQFPYELRVSDYDGYNQFVVHRSPQPLMSPAWSPDGSKLAYVTFESGRSALVIQTLANGAVRQVASFPRHNGAPAFSPDGSKLAFALSKTGSLNLYVMDLASGQIRQVTDGRSNNTEPTWFPDSQNLAFTSDQAGRPQVYKVNINGGAPQRITWEGSQNQDADVSSDGKFMVMVSSNGGQQHIAKQDLATGGVQVLSSTFLDETPSLAPNGTMVIYSSSQGMGSVLNLVSTDGRFKARLPATDGQVKFPAWSPYL*
--BBBB-BBBBBBBBB---BBBBBBB----HHHHHHHHHHH--BBBB--HHH-------HHH--HHHHHCCC--BBBBBBBBB-----BBBBBBBBB-BBB---BBBBBBBBB-HHHHHHHHHHHHHHHHHHHH--------BBBBBBB-BBBB--BBBBBBB------BBBBBBBB-BBBBBB---BBBBBBBB------BBBBBBCCC--BBBBB-----BBBBBB---BBBBBBBB------BBBBBBCCC--BBB---BBB-BBBBBB---BBBBBBBB------BBBBBB-----------BBBBBBBBBB---BBBBBBBBB----BBBBBBBCCC--BBB---BBB-BBBBB---BBBBBBBBBB--BBBBBBBB-----BBB---BBBBBBBBBB----*

>2GS5:A|PDBID|CHAIN|SEQUENCE
MFADRLFNAMERNEPAPGMVLVAAPSMESEDFARSVILIIEHSEYATFGVNLASRSDVAVFNVIPEWVPCVTKPQALYIGGPLNQQSVVGVGVTAQGVDAARVDNLTRLANRLVMVNLGADPEEIKPLVSGMRLFAGHAEWAPGQLAQEIENGDWFVAPALPSDVTAPGSVDVWGDVMRRQPMPLPLYSTFPVNVGEN*
---HHHH-----------BBBBB------------BBBBBBB----BBBBB---BBBBBHHH--HHHHHH-----BBBB---BBBBBBBBBBBB-----HHH----BBBB--BBB------HHHHHHHBBBBBBBBBBBBB---HHHHHHH---BBBBB--HHHHH------HHHHHHH-----HHHH----------*

>2F21:A|PDBID|CHAIN|SEQUENCE
MADEEKLPPGWEKRMSRSSGRVYYFNHITNASQWERPSGNSSSGGKNGQGEPARVRCSHLLVKHSQSRRPSSWRQEKITRTKEEALELINGYIQKIKSGEEDFESLASQFSDCSSAKARGDLGAFSRGQMQKPFEDASFALRTGEMSGPVFTDSGIHIILRTE*
----------BBBBB-CCC--BBBBBCCC--BBBB---BBB-----------BBBBBBBBBB----BBB-----BBB----HHHHHHHHHHHHHHHHHBBB-HHHHHHHH---HHHHH--BBBBBB-----HHHHHHHHH---------BBB--BBBBBBBBB*

>2BKF:A|PDBID|CHAIN|SEQUENCE
MEPQVTLNVTFKNEIQSFLVSDPENTTWADIEAMVKVSFDLNTIQIKYLDEENEEVSINSQGEYEEALKMAVKQGNQLQMQVHEG*
----EEEEEEE--EEEEEEEE-HHH--HHHHHHHHHHHH-BBBBBBBBB-----BBBB--HHHHHHHHHHHHHCCCBBBBBBBB-*

>2FC3:A|PDBID|CHAIN|SEQUENCE
MSKPIYVRFEVPEDLAEKAYEAVKRARETGRIKKGTNETTKAVERGLAKLVVIAEDVDPPEIVMHLPLLCDEKKIPYVYVPSKKRLGEAAGIEVAAASVAIIEPGDAETLVREIVEKVKELRAKAGV*
------------HHHHHHHHHHHHHHHHHBBBBBBHHHHHHHHH----BBBBBB-----HHHCCCHHHHHHH----BBBBB-HHHHHHH-------BBBBBBB-HHHHHHHHHHHHHHHHHHHHH--*

>2FH1:A|PDBID|CHAIN|SEQUENCE
MDDDGTGQKQIWRIEGSNKVPVDPATYGQFYGGDSYIILYNYRHGGRQGQIIYNWQGAQSTQDEVAASAILTAQLDEELGGTPVQSRVVQGKEPAHLMSLFGGKPMIIYKGGTSREGGQTAPASTRLFQVRANSAGATRAVEVLPKAGALNSNDAFVLKTPSAAYLWVGTGASEAEKTGAQELLRVLRAQPVQVAEGSEPDGFWEALGGKAAYRTSPRLKDKKMDAHPPRLFACSNKIGRFVIEEVPGELMQEDLATDDVMLLDTWDQVFVWVGKDSQEEEKTEALTSAKRYIETDPANRDRRTPITVVKQGFEPPSFVGWFLGWDDDYWSVDPLDRAMAELAA*
------BBBBBBBBB--BBBB--HHH--BBB--BBBBBBBBBBB--BBBBBBBBBB-----HHHHHHHHHHHHHHHHHCCC-BBBBBBB-----HHHHHHH----BBBBB----CCC------BBBBBBBBB-----BBBBBB----HHH---BBBBBB----BBBBB-----HHHHHHHHHHHHH-----BBBB-----HHHHHHBBB-------HHHH--HHHH---BBBBBB-CCC--BBBBB-----HHH----BBBBBB----BBBBB-----HHHHHHHHHHHHHHHH-----------BBBBB-----HHHH--BBB--BBB----HHHHHHH----*

>2E64:A|PDBID|CHAIN|SEQUENCE
MLGLKTSIIGRRVIYFQEITSTNEFAKTSYLEEGTVIVADKQTMGHGALNRKWESPEGGLWLSIVLSPKVPQKDLPKIVFLGAVGVVETLKEFSIDGRIKWPNDVLVNYKAIAGVLVEGKGDKIVLGIGLNVNNKVPNGATSMKLELGSEVPLLSVFRSLITNLDRLYLNFLKNPMDILNLVRDNMILGVRVKILGDGSFEGIAEDIDDFGRLIIRLDSGEVKKVIYGDVSLRFL*
-----------BBBBB-----HHHHHHH-------BBBB--------HHH---------BBBBBBB-----HHHHHHHHHHHHHHHHHHHHH-----BBB---BBBB--BBBBBBBBBBB--BBBBBBBB------------HHHHH-----HHHHHHHHHHHHHHHHHHHHH---HHHHHHHHH----BBBBBB---BBBBBBBBB-----BBBB-----BBBB-----BBBB-*

>2ESO:A|PDBID|CHAIN|SEQUENCE
MALKRIHKELNDLARDPPAQCSAGPVGDDMFHWQATAMGPNDSPYQGGVFFLTIHFPTDYPFKPPKVAFTTRIYHPNINSNGSICLDILRSQWSPALTISKVLLSICSLLCDPNPDDPLVPEIARIYKTDREKYNRIAREWTQKYAM*
HHHHHHHHHHHHHHH---BBBBBBBBBB---BBBBBBB--BBBCCCC-BBBBBBB--CCCC----BBBBBB----BBB---BBB--HHHCCC------HHHHHHHHHHHHH---BBB---HHHHHHHHH-HHHHHHHHHHHHHHH--*

>2CZ8:A|PDBID|CHAIN|SEQUENCE
MGKVYKKVELVGTSEEGLEAAIQAALARARKTLRHLDWFEVKEIRGTIGEAGVKEYQVVLEVGFRLEET*
---BBBBBBBBBBB---HHHHHHHHHHHHHHH---BBBBBBBBBBBBBB--BBBBBBBBBBBBBB----*

>2ASB:A|PDBID|CHAIN|SEQUENCE
GEFSTREGEIVAGVIQRDSRANARGLVVVRIGTETKASEGVIPAAEQVPGESYEHGNRLRCYVVGVTRGAREPLITLSRTHPNLVRKLFSLEVPEIADGSVEIVAVAREAGHRSKIAVRSNVAGLNAKGACIGPMGQRVRNVMSELSGEKIDIIDYDDDPARFVANALSPAKVVSVSVIDQTARAARVVVPDFQLSLAIGKEGQNARLAARLTGWRIDIRGDAPPPPPGQPEPGVSRGMAHDRLE*
---------BBBBBBB--HHHHH---BBBBB-BBBB-BBBBB-HHH-----------BBBBBBBBBB--BBB-BBBBBBB-HHHHHHHHHHH-HHHH--BBBBBBBBBBCCCBBBBBBBBBB----HHHHHH-HHHHHHHHHHHHCCC-BBBBBB----HHHHHHHHCCC---BBBBBBBCCCCBBBBBB-HHHHHHHH-HHHHHHHHHHHHH--BBBBBBBB----------------------*

>2CC9:A|PDBID|CHAIN|SEQUENCE
MVFKKVLLTGTSEESFTAAADDAIDRAEDTLDNVVWAEVVDQGVEIGAVEERTYQTEVQVAFELDGSQ*
--BBBBBBBBBB---HHHHHHHHHHHHHHH---BBBBBBBBBBBB-------BBBBBBBBBBB-----*

>2CFG:A|PDBID|CHAIN|SEQUENCE
MTPSTIQTASPFRLASAGEISEVQGILRTAGLLGPEKRIAYLGVLDPARGAGSEAEDRRFRVFIHDVSGARPQEVTVSVTNGTVISAVELDTAATGELPVLEEEFEVVEQLLATDERWLKALAARNLDVSKVRVAPLSAGVFEYAEERGRRILRGLAFVQDFPEDSAWAHPVDGLVAYVDVVSKEVTRVIDTGVFPVPAEHGNYTDPELTGPLRTTQKPISITQPEGPSFTVTGGNHIEWEKWSLDVGFDVREGVVLHNIAFRDGDRLRPIINRASIAEMVVPYGDPSPIRSWQNYFDTGEYLVGQYANSLELGCDCLGDITYLSPVISDAFGNPREIRNGICMHEEDWGILAKHSDLWSGINYTRRNRRMVISFFTTIGNYDYGFYWYLYLDGTIEFEAKATGVVFTSAFPEGGSDNISQLAPGLGAPFHQHIFSARLDMAIDGFTNRVEEEDVVRQTMGPGNERGNAFSRKRTVLTRESEAVREADARTGRTWIISNPESKNRLNEPVGYKLHAHNQPTLLADPGSSIARRAAFATKDLWVTRYADDERYPTGDFVNQHSGGAGLPSYIAQDRDIDGQDIVVWHTFGLTHFPRVEDWPIMPVDTVGFKLRPEGFFDRSPVLDVPANPSQSGSHCHGSNWSHPQFEK*
----------------HHHHHHHHHHHHH--BBB--BBBBBBBB-------BBBB---BBBBBBBB------BBBBBBCCCCBBBBBBB--HHHH------HHH--HHHHHH---HHHHHHHHH----HHHBBBBBBB--BBB-HHH----BBBB-BBB-------HHH-----BBBBBBCCCCBBBBBBB---------------HHHH----------BBB-------BBBCCCBBBB--BBBBBBBBCCCBBBBBBBBBBB--BBBBBBBBBBBBBBBBBB----CCCCC-BBBHHHHH-HHHH-----CCC------BBB--BBB-----BBB----BBBBBBBBBBBBBBB-CCC--BBBBBBBBBBBBBBBBB--BBBBBBBBBB----BBBBBBBBB------------BBBBBBB--BBBB-BBBBBBBBBBB------BBBBBBBBBB----CCC-----BBBBBBB---HHH------HHH--BBBBBBBBBB-----BBBBBBBB------------HHHHH-HHHHBBBBBBB-----------------BBBBHHHHH------BBB-BBBBBBBBBBB---HHHBBBBBBBBBBBBBBBBB-BBB-CCCC------------------------*

>2CYZ:A|PDBID|CHAIN|SEQUENCE
MSVTIDHTTENAAPAQAPVSDRAWALFRALDGKGLVPDGYVEGWKKTFEEDFSPRRGAELVARAWTDPEFRQLLLTDGTAAVAQYGYLGPQGEYIVAVEDTPTLKNVIVCSLCSCTAWPILGLPPTWYKSFEYRARVVREPRKVLSEMGTEIASDIEIRVYDTTAETRYMVLPQRPAGTEGWSQEQLQEIVTKDCLIGVAIPQVPTV*
------------------HHHHHHHHHHHHHCCC-----HHHHHHHHHHH---HHHHHHHHHHHHH-HHHHHHHHH-HHHHHHH-------BBBBBBBB----BBBBBB--------HHHH----HHHH-HHHHHHCCC-HHHHHHHH-------BBBBBBB--BBBBBBBB-----------HHHHHHH--HHHHHBBB-------*

>2PC2:A|PDBID|CHAIN|SEQUENCE
KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL*
----HHHHHHHHHHCCCCCHHH--HHHHHHHHHHHHBBB---BBB-BBB-BBBCCCC--CCCC---BBB----------HHHHHBBB-HHHHHHHHHHHHBBB-HHH-HHHHHHCCC--HHHHCCC---*

>2Q0I:A|PDBID|CHAIN|SEQUENCE
MLRLSAPGQLDDDLCLLGDVQVPVFLLRLGEASWALVEGGISRDAELVWADLCRWVADPSQVHYWLITHKHYDHCGLLPYLCPRLPNVQVLASERTCQAWKSESAVRVVERLNRQLLRAEQRLPEACAWDALPVRAVADGEWLELGPRHRLQVIEAHGHSDDHVVFYDVRRRRLFCGDALGEFDEAEGVWRPLVFDDMEAYLESLERLQRLPTLLQLIPGHGGLLRGRLAADGAESAYTECLRLCRRLLWRQSMGESLDELSEELHRAWGGQSVDFLPGELHLGSMRRMLEILSRQALPLD*
-BBB-BBBBBB--BBBBB-----BBBBBBB--BBBBB----HHHHHHHHHHHHHH---HHHBBBBB-----CCCCCCHHHHHHH----BBBBBHHHHHH---HHHHHHHHHHHHH-------------HHH--BBBB----BBBBB--BBBBBBB--BBB---BBBBBCCCCBBBBBCCC-BBBCCC-BBB------HHHHHHHHHHHH-----BBBBBBBB-BBBHHHHH-HHHHHHHHHHHHHHHHHHHHH----HHHHHHHHHHHHHHHHCCC--HHHHHHHHHHHHHHHHHH-----*

>2Q3U:A|PDBID|CHAIN|SEQUENCE
MEESRESPAEHGYYMPAEWDSHAQTWIGWPERQDNWRHNALPAQRVFAGVAKAISKFEPVTVCASPAQWENARKQLPEDIRVVEMSMNDSWFRDSGPTFIVRKRPVKLSSLNRNIAGIDWNFNAWGGANDGCYNDWSHDLLVSRKILALERIPRFQHSMILEGGSIHVDGEGTCLVTEECLLNKNRNPHMSKEQIEEELKKYLGVQSFIWLPRGLYGDEDTNGHIDNMCCFARPGVVLLSWTDDETDPQYERSVEALSVLSNSIDARGRKIQVIKLYIPEPLYMTEEESSGITQDGEAIPRLAGTRLAASYVNFYIANGGIIAPQFGDPIRDKEAIRVLSDTFPHHSVVGIENAREIVLAGGNIHCITQQQPAEPTSVAENGH*
--------HHH----------BBBBBB-----CCC--HHHHHHHHHHHHHHHHHH----BBBBB-HHHHHHHHHH----BBBBB-------HHHH--BBBB------------BBBBBBBB--CCCHHHH-BBB----HHHHHHHHHHHH---BBBBBBB--HHHBBB-BBBBBBBBHHHH--CCC-----HHHHHHHHHHHH---BBBBBB------HHH---HHH-BBBBB--BBBBBB-------HHHHHHHHHHHHH----------BBBBBB--------HHHHH-----BBB----------------BBB--BBBBB------HHHHHHHHHHHH---BBBBBBCCCHHHHCCC--HHHHBBBBB-----------*

>2Q5A:A|PDBID|CHAIN|SEQUENCE
MADEEKLPPGWEKAMSRSSGRVYYFNHITNASQWERPSGNSSSGGKNGQGEPARVRCSHLLVKHSQSRRPSSWRQEKITRTKEEALELINGYIQKIKSGEEDFESLASQFSDCSSAKARGDLGAFSRGQMQKPFEDASFALRTGEMSGPVFTDSGIHIILRTE*
----------BBBBB-CCC--BBBBBCCC--BBBB---BBB-----------BBBBBBBBBB----BBB-----BBB----HHHHHHHHHHHHHHHHHBBB-HHHHHHHH---HHHHH--BBBBBB-----HHHHHHHHH---------BBB--BBBBBBBBB*

>2QIF:A|PDBID|CHAIN|SEQUENCE
MEQKTLQVEGMSCQHCVKAVETSVGELDGVSAVHVNLEAGKVDVSFDADKVSVKDIADAIEDQGYDVAK*
-BBBBBBBB----HHHHHHHHHHHH----BBBBBBBCCCCBBBBBB-CCC--HHHHHHHHHH----BBB*

>2QSW:A|PDBID|CHAIN|SEQUENCE
KNIEETELVVEEMLEQYPNGKIVRLLFHGEQAKLPIISHIVQEYQVEVSIIQGNIQQTKQGAVGSLYIQLLGEEQNILAAIEGLRKLRVETEVIGNE*
---------HHHHHHH--BBBBBBBBBBB------HHHHHHHHH--BBBBBBBBBBBB--BBBBBBBBBBBB-HHHHHHHHHHHHH---BBBBBB--*

>2RAT:A|PDBID|CHAIN|SEQUENCE
KETAAAKFERQHMDSSTSAASSSNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMSITDCRETGSSKYPNCAYKTTQANKHIIVACEGNPYVPVHFDASV*
---HHHHHHHHH----BBB--HHHHHHHHHHH--BBBBB--BBBBBB----BBBBBBBBBBBB--BBB---BBB-BBBBBBBBBBB-----BBB--BBBBBBBB-BBBBBBCCCCBBBBBBBB-*

>2BMR:A|PDBID|CHAIN|SEQUENCE
MSYQNLVSEAGLTQKLLIHGDKELFQHELKTIFARNWLFLTHDSLIPSPGDYVKAKMGVDEVIVSRQNDGSVRAFLNVCRHRGKTLVHAEAGNAKGFVCGYHGWGYGSNGELQSVPFEKELYGDAIKKKCLGLKEVPRIESFHGFIYGCFDAEAPPLIDYLGDAAWYLEPTFKYSGGLELVGPPGKVVVKANWKSFAENFVGDGYHVGWTHAAALRAGQSVFSSIAGNAKLPPEGAGLQMTSKYGSGMGVFWGYYSGNFSADMIPDLMAFGAAKQEKLAKEIGDVRARIYRSFLNGTIFPNNSFLTGSAAFRVWNPIDENTTEVWTYAFVEKDMPEDLKRRVADAVQRSIGPAGFWESDDNENMETMSQNGKKYQSSNIDQIASLGFGKDVYGDECYPGVVGKSAIGETSYRGFYRAYQAHISSSNWAEFENASRNWHIEHTKTTDR*
--------HHH-BBBHHHH--HHHHHHHHHH------BBBBBHHH-----BBBBBBB--BBBBBB------BBBBB--------------BBB--BBBB-----BBB----BBB---HHHH-HHH--HHH-------BBBBB--BBBBB-------HHHHH--HHHHHHHHH-----BBBBBBBBBBBB---HHHHHHHHHH-HHHHHHH-HHHHHHH--HHHHHHHH---------BBBB-----BBBBB---------HHHHHHHHHHHHHHHHHHHHHH-HHHHHHH--BBBBBB---BBBB----BBBBBBBBB--BBBBBBBBBBB----HHHHHHHHHHHHHHH----HHHHHHHHHHHHHHHH-----HHH-BBB--------BB-------BBB------HHHHHHHHHHHHHH----HHHHHHH--------------*

>2BT6:A|PDBID|CHAIN|SEQUENCE
DKITVHFINRDGETLTTKGKIGDSLLDVVVQNNLDIDGFGACEGTLACSTCHLIFEQHIFEKLEAITDEENDMLDLAYGLTDRSRLGCQICLTKAMDNMTVRVP*
-BBBBBBB-BBB-BBBBBBB----HHHHHHH-----CCCCCCBBBBBBB--BBB--HHHH-------HHHHHHH------BBBBBBHHH----HHH--BBBB--*

>2B0V:A|PDBID|CHAIN|SEQUENCE
GHMTWKPNVTVAAVIEQDDKYLLVEEIPRGTAIKLNQPAGHLEPGESIIQACSREVLEETGHSFLPEVLTGIYHWTCASNGTTYLRFTFSGQVVSFDPDRKLDTGIVRAAWFSIDEIRAKQAMHRTPLVMQCIEDYHAGKRYPLDILQYYDGS*
-----BBBBBBB-BB--BBBBBBB-------BBB--BBB-----HHHHHHHHHHHHHH--BBBBBBBBBBBBBBB----BBBBBBBBBBBBBBB---------BBBBBBBBHHHHHH-HHH----HHHHHHHHHH------HHH---------*

>2AAY:A|PDBID|CHAIN|SEQUENCE
MESLTLQPIARVDGTINLPGSKSVSNRALLLAALAHGKTVLTNLLDSDDVRHMLNALTALGVSYTLSADRTRCEIIGNGGPLHAEGALELFLGNAGTAMRPLAAALCLGSNDIVLTGEPRMKERPIGHLVDALRLGGAKITYLEQENYPPLRLQGGFTGGNVDVDGSVSSQFLTALLMTAPLAPEDTVIRIKGDLVSKPYIDITLNLMKTFGVEIENQHYQQFVVKGGQSYQSPGTYLVEGDASSASYFLAAAAIKGGTVKVTGIGRNSMQGDIRFADVLEKMGATICWGDDYISCTRGELNAIDMDMNHIPDAAMTIATAALFAKGTTTLRNIYNWRVKETDRLFAMATELRKVGAEVEEGHDYIRITPPEKLNFAEIATYNDHRMAMCFSLVALSDTPVTILDPKCTAKTFPDYFEQLARISQAA*
--BBBB----BBBBBBB----HHHHHHHHHHHHHBBBBBBBBB-----HHHHHHHHHHH---BBBB-BBB--BBBB--BBB------BBBB----HHHHHHHHHH--BBBBBBBBB--HHHHH---HHHHHHHHH----BBBBBB-----BBBBB----BBBBBBBBB--HHHHHHHHHHHHBBB-BBBBBBBBB---HHHHHHHHHHHH-----BBBCCCBBBB---------BBBB----HHHHHHHHHHHHHHBBBBBBBB-------HHHHHHHHHHHH--BBBB-BBBBBBB-------BBB----CCCHHHHHHHHHHBBB-BBBBB-HHHHHBBB-HHHHHHHHHHH---BBBB-BBBBBBB---------------HHHHHHHHHHHBBBB-BBBBBHHHHH-----HHHHHHHH----*

>2AL1:A|PDBID|CHAIN|SEQUENCE
MAVSKVYARSVYDSRGNPTVEVELTTEKGVFRSIVPSGASTGVHEALEMRDGDKSKWMGKGVLHAVKNVNDVIAPAFVKANIDVKDQKAVDDFLISLDGTANKSKLGANAILGVSLAASRAAAAEKNVPLYKHLADLSKSKTSPYVLPVPFLNVLNGGSHAGGALALQEFMIAPTGAKTFAEALRIGSEVYHNLKSLTKKRYGASAGNVGDEGGVAPNIQTAEEALDLIVDAIKAAGHDGKVKIGLDCASSEFFKDGKYDLDFKNPNSDKSKWLTGPQLADLYHSLMKRYPIVSIEDPFAEDDWEAWSHFFKTAGIQIVADDLTVTNPKRIATAIEKKAADALLLKVNQIGTLSESIKAAQDSFAAGWGVMVSHRSGETEDTFIADLVVGLRTGQIKTGAPARSERLAKLNQLLRIEEELGDNAVFAGENFHHGDKL*
----BBBBBBBB-----BBBBBBBBB--BBBBBB--------BBB-----------HHH---HHHHHHHHH-HHHHHHHH------HHHHHHHHHHHH-BBB-CCC-HHHHHHHHHHHHHHHHHH----HHHHHHHHH------BBB----BBBBB-HHHBBBB----BBBBB------HHHHHHHHHHHHHHHHHHHHHHH-HHHH-----BBB------HHHHHHHHHHHHHHH--CCC-BBBBB--HHHH-------CCCC-----HHH---HHHHHHHHHHHHHH--BBBBB-------HHHHHHHHCCC-BBBBBBCCCCCC-HHHHHHHH----BBBBB-HHHH--HHHHHHHHHHHHH---BBBBB---------HHHHHHHH---BBBB------HHHHHHHHHHHHHHHHHHHHBBB-HHH---HHH-*

>2BMR:B|PDBID|CHAIN|SEQUENCE
MMINTQEDKLVSAHDAEEFHRFFVGHDSDLQQEVTTLLTREAHLLDIQAYKAWLEHFVAPEIKYQVISRELRSTSERRYQLNDAVNLYNENYQQLKVRVEHQMDPQNWANNPKIRFTRFVTNVTAAKDKSAPEILHVRSNLILHRARRENQVDVFYATREDKWKRIEGGGIKLVERFVDYPERIPQTHNLLVFL*
------------HHHHHHHHHHHH---HHHHHHHHHHHHHHHHHHH---HHHHHHHHBBBBBBBBBBBB--------------BBBBBBB-HHHHHHHHHHHH----HHH----BBBBBBBBBBBBB------BBBB-------------BBBBBBBBBBBBBBB-----BBBBBBBBB---------------*

>2A7L:A|PDBID|CHAIN|SEQUENCE
MASMQKRLQKELLALQNDPPPGMTLNEKSVQNSITQWIVDMEGAPGTLYEGEKFQLLFKFSSRYPFDSPQVMFTGENIPVHPHVYSNGHICLSILTEDWSPALSVQSVCLSIISMLS*
-----HHHHHHHHHHHH-----------------BBBBBBBB-----CCCC-BBBBBBBB-CCCCC---BBBBBB-----------------HHHCCC------HHHHHHHHHHH--*

>2A7F:A|PDBID|CHAIN|SEQUENCE
KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL*
----HHHHHHHHHHCCCCCHHH--HHHHHHHHHHHHBBB---BBB-BBB-BBBCCCC--CCCC---BBB----------HHHHHBBB-HHHHHHHHHHHHBBB-HHH-HHHHHHCCC--HHHHCCC---*

>2A89:A|PDBID|CHAIN|SEQUENCE
MSTHFDVIVVGAGSMGMAAGYQLAKQGVKTLLVDAFDPPHTNGSHHGDTRIIRHAYGEGREYVPLALRSQELWYELEKETHHKIFTKTGVLVFGPKGESAFVAETMEAAKEHSLTVDLLEGDEINKRWPGITVPENYNAIFEPNSGVLFSENCIRAYRELAEARGAKVLTHTRVEDFDISPDSVKIETANGSYTADKLIVSMGAWNSKLLSKLNLDIPLQPYRQVVGFFESDESKYSNDIDFPGFMVEVPNGIYYGFPSFGGCGLKLGYHTFGQKIDPDTINREFGVYPEDESNLRAFLEEYMPGANGELKRGAVCMYTKTLDEHFIIDLHPEHSNVVIAAGFSGHGFKFSSGVGEVLSQLALTGKTEHDISIFSINRPALKESLQKTTI*
----BBBBBB---HHHHHHHHHHHH----BBBB-------BBBBB-BBBBBB-------HHHHHHHHHHHHHHHHHHHH----------BBBBBBCCC-HHHHHHHHHHHH-----BBBB-HHHHHH---------BBBBBB---BBBBHHHHHHHHHHHHHH---BBB----BBBBBB----BBBBB--BBBBBBBBBB--HHHHHHHHHHH------BBBBBBBBBB---HHHH-HHH---BBBBBB--BBBBBB-------BBBBBBB------CCC------BBBHHHHHHHHHHHHH-HHH---BBBBBBBBBBB-BBB--BBBBB--BBBBBBBB------HHHHHHHHHHHHHHHHH-------HHH----HHH--BBB----*

>2A8K:A|PDBID|CHAIN|SEQUENCE
LAKNKGKIPGLKIDQKIRGQMPERGWTEDDIKNTVSNGATGTSFDKRSPKKTPPDYLGRNDPATVYGSPGKYVVVNDRTGEVTQISDKTDPGWVDDSRIQWGNKNDQ*
----------------HHHHHHHH----HHHHHHHHH----BBBBBBB-HHH-CCC---BBBBBBBBBB--BBBBBBCCC-BBBBB---------------BBB---*

>2A4T:A|PDBID|CHAIN|SEQUENCE
MNIFEMLRIDEGLRLKIYKDTEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAACNLAKSRWYNQTPNRAKRVITTFRTGTWDAYKNL*
--HHHHHHHHH--BBBBBB-BBB-BBBB--BBB-BBB-HHHHHHHHHHHH----BBB----HHH---HHHHHHHHHHHH--CCCHHHHHH--HHHHHHHHHHHHHH-HHHHH--HHHHHHHHCCCHHHHHHHH---HHHHH-HHHHHHHHHHHHHBBBCCCHHH*

>2A5D:A|PDBID|CHAIN|SEQUENCE
MGKVLSKIFGNKEMRILMLGLDAAGKTTILYKLKLGQSVTTIPTVGFNVETVTYKNVKFNVWDVGGQDKIRPLWRHYYTGTQGLIFVVDCADRDRIDEARQELHRIINDREMRDAIILIFANKQDLPDAMKPHEIQEKLGLTRIRDRNWYVQPSCATSGDGLYEGLTWLTSNYKS*
--HHHHHHH---BBBBBBB------HHHHHHHHHH---BBBBBBBBBBBBBBBB--BBBBBBBBHHHHHHHHHHHHHCCC--BBBBBBB---HHHHHHHHHHHHHHH--HHH---BBBBBBB--BBBB---HHHHHHH--HHH-----BBBBB--CCCC--HHHHHHHHHHH---*

>2A5D:B|PDBID|CHAIN|SEQUENCE
NDDKLYRADSRPPDEIKQSGGLMPRGQSEYFDRGTQMNINLYDHARGTQTGFVRHDDGYVSTSISLRSAHLVGQTILSGHSTYYIYVIATAPNMFNVNDVLGAYSPHPDDQDVSALGGIPYSQIYGWYRVHFGVLDEQLHRNRGYRDRYYSNLDIAPAADGYGLAGFPPEHRAWREEPWIHHAPPGSGNAPR*
---BBBBBBBB-HHHHHHH-----HHH-----BBB-----HHHHHH-----BBB----BBBBBBBHHHHHHHHHHHCCC-BBBBBBBBB----BBBHHHHHHHH---HHH--BBBB----HHHBBBBBBBB--BBB-BBBB-----HHHHH------HHH-HHH-------HHH----HHHH----------*

>2A6S:A|PDBID|CHAIN|SEQUENCE
MKLIWSEESWDDYLYWQETDKRIVKKINELIKDTRRTPFEGKGKPEPLKHNLSGFWSRRITEEHRLVYAVTDDSLLIAACRYHY*
-BBBB-HHHHHHHHHHH---HHHHHHHHHHHHHHHH-------------HHH---BBBBBBBB-BBBBBB-BBBBBBBBBB---*

>2A78:A|PDBID|CHAIN|SEQUENCE
MAANKPKGQNSLALHKVIMVGSGGVGKSALTLQFMYDEFVEDYEPTKADSYRKKVVLDGEEVQIDILDTAGQEDYAAIRDNYFRSGEGFLCVFSITEMESFAATADFREQILRVKEDENVPFLLVGNKSDLEDKRQVSVEEAKNRAEQWNVNYVETSAKTRANVDKVFFDLMREIRARKMEDS*
-------------BBBBBBB------HHHHHHHHHH------------BBBBBBBBB--BBBBBBBBB-------HHHHHHHHHH-BBBBBBBB---HHHHHHHHHHHHHHHHHH------BBBBBB-HHHHHH----HHHHHHHHHH---BBBB--CCC---HHHHHHHHHHHHHHHHH---*

>2A3E:A|PDBID|CHAIN|SEQUENCE
MRFATSTIVKVALLLSSLCVDAAVMWNRDTSSTDLEARASSGYRSVVYFVNWAIYGRNHNPQDLPVERLTHVLYAFANVRPETGEVYMTDSWADIEKHYPGDSWSDTGNNVYGCIKQLYLLKKQNRNLKVLLSIGGWTYSPNFAPAASTDAGRKNFAKTAVKLLQDLGFDGLDIDWEYPENDQQANDFVLLLKEVRTALDSYSAANAGGQHFLLTVASPAGPDKIKVLHLKDMDQQLDFWNLMAYDYAGSFSSLSGHQANVYNDTSNPLSTPFNTQTALDLYRAGGVPANKIVLGMPLYGRSFANTDGPGKPYNGVGQGSWENGVWDYKALPQAGATEHVLPDIMASYSYDATNKFLISYDNPQVANLKSGYIKSLGLGGAMWWDSSSDKTGSDSLITTVVNALGGTGVFEQSQNELDYPVSQYDNLRNGMQT*
-------------------------------------------BBBBBBBHHHH------HHH--HHH--BBBBBBBBB------BBB--HHHHH-----------------HHHHHHHHHHHH----BBBBBBB----HHHHHHH---HHHHHHHHHHHHHHHHHH---BBBBB------HHHHHHHHHHHHHHHHHHHHHHHHH------BBBBBB---HHHHHH--HHHHHHH--BBBB-------------------------HHH----HHHHHHHHHH----HHHBBBBBB-BBBBB---------------------BBBHHH------BBBBBHHH-BBBBBB----BBBB---HHHHHHHHHHHHHH---BBBBB-HHH---HHH-HHHHHHHHH--HHH---------------HHHH-----*

>2A40:A|PDBID|CHAIN|SEQUENCE
MCDEDETTALVCDNGSGLVKAGFAGDDAPRAVFPSIVGRPRHQGVMVGMGQKDSYVGDEAQSKRGILTLKYPIEHGIITNWDDMEKIWHHTFYNELRVAPEEHPTLLTEAPLNPKANREKMTQIMFETFNVPAMYVAIQAVLSLYASGRTTGIVLDSGDGVTHNVPIYEGYALPHAIMRLDLAGRDLTDYLMKILTERGYSFVTTAEREIVRDIKEKLCYVALDFENEMATAASSSSLEKSYELPDGQVITIGNERFRCPETLFQPSFIGMESAGIHETTYNSIMKCDIDIRKDLYANNVMSGGTTMYPGIADRMQKEITALAPSTMKIKIIAPPERKYSVWIGGSILASLSTFQQMWITKQEYDEAGPSIVHRKCF*
---CCCCC-BBBBB-BBBBBBBB--BBB-BBBBB--BBBB-CCC---BBB---BBBHHHHHHH--BBBBB-BBB------HHHHHHHHHHHHHCCC---HHH--BBBBB-----HHHHHHHHHHHHH----BBBBBBBHHHHHHHH---BBBBBBBBBBB-BBBBBBB-----HHH-BBBB--HHHHHHHHHHHHHHH------HHHHHHHHHHHHHH------HHHHHHHHHH-BBB-BBBB-BBB-BBBBB-HHHHHHHCCC-HHHH------HHHHHHHHHH---HHHHHHHH--BBBBBHHH-BBBHHHHHHHHHHHH-HHH--------CCCC-HHHHHHHHHHH-HHHHHHBBBHHHHHHH-HHHH-----*

>2A40:B|PDBID|CHAIN|SEQUENCE
LKIAAFNIRTFGETKMSNATLASYIVRIVRRYDIVLIQEVRDSHLVAVGKLLDYLNQDDPNTYHYVVSEPLGRNSYKERYLFLFRPNKVSVLDTYQYDDGCESCGNDSFSREPAVVKFSSHSTKVKEFAIVALHSAPSDAVAEINSLYDVYLDVQQKWHLNDVMLMGDFNADCSYVTSSQWSSIRLRTSSTFQWLIPDSADTTATSTNCAYDRIVVAGSLLQSSVVPGSAAPFDFQAAYGLSNEMALAISDHYPVEVTLT*
-BBBBBBBBBBBHHHHH-HHHHHHHHHHH---BBBBBBBB--BBBHHHHHHHHHH-BBB----BBBB-----BBB--BBBBBBB-CCC-BBBBBBB--BBBCCCHHHH-----BBBBBB---BBBBBBBBBB----HHHHHHHHHHHHHHHHHHHHHH----BBBBBB----CCC--HHHHHH-HHHH---BBBBB------BBBB-----BBBBBBBHHHHHH----------HHHH----HHHHHHH-----BBBBB-*

>260L:A|PDBID|CHAIN|SEQUENCE
MNIFEMLRIDEGLRLKIYKDHEGYYTIGIGHLLTKSPSLNAAKSELDKAIGRNTNGVITKDEAEKLFNQDVDAAVRGILRNAKLKPVYDSLDAVRRAALINMVFQMGETGVAGFTNSLRMLQQKRWDEAAVNLAKSRWYNQHPNRAKRVITTFRTGTWDAYKNL*
--HHHHHHHHH-BBBBBBB-----BBBBB-BBBB----HHHHHHHHHHHH---------HHHHHHHHHHHHHHHHHHHHH---HHHHHH---HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH---HHHHHHHHHH-HHHHH-HHHHHHHHHHHHH--HHHH---*

>2A10:A|PDBID|CHAIN|SEQUENCE
MSAQSAVGSIETIGFPGILAAADAMVKAGRITIVGYIRAGSARFTLNIRGDVQEVKTAMAAGIDAINRTEGADVKTWVIIPRPHENVVAVLPIDFSPEVEPFREAAEGLNRR*
-----BBBBBBBBBHHHHHHHHHHHHHH---BBBBBBBBB--BBBBBBBB-HHHHHHHHHHHHHHHH------BBBBBBBBB--HHHHHH------HHHHHHHHHH------*

>1ZXI:A|PDBID|CHAIN|SEQUENCE
MAKAHIELTINGHPVEALVEPRTLLIHFIREQQNLTGAHIGCDTSHCGACTVDLDGMSVKSCTMFAVQANGASITTIEGMAAPDGTLSALQEGFRMMHGLQCGYCTPGMIMRSHRLLQENPSPTEAEIRFGIGGNLCRCTGYQNIVKAIQYAAAKINGVPFEEAAE*
---BBBBBBB--BBBBBBB-----HHHHHHH-----------BBB-----BBBB--BBBBHHH--HHHH---BBB-HHH---------HHHHHHHH---------HHHHHHHHHHHHHH-----HHHHHHHCCC---BBB--HHHHHHHHHHHHHHH---------*

>1ZXI:C|PDBID|CHAIN|SEQUENCE
MIPGSFDYHRPKSIADAVALLTKLGEDARPLAGGHSLIPIMKTRLATPEHLVDLRDIGDLVGIREEGTDVVIGAMTTQHALIGSDFLAAKLPIIRETSLLIADPQIRYMGTIGGNAANGDPGNDMPALMQCLGAAYELTGPEGARIVAARDYYQGAYFTAIEPGELLTAIRIPVPPTGHGYAYEKLKRKIGDYATAAAAVVLTMSGGKCVSASIGLTNVANTPLWAEEAGKVLVGTALDKPALDKAVALAEAITAPASDGRGPAEYRTKMAGVMLRRAVERAKARAKN*
------BBB----HHHHHHHHHHHHHHBBBBBB---HHHHHH------BBBBB----HHH--BBBB--BBBBB----HHHHHH-HHHHHH-HHHHHHH-----HHHHHH--HHHHHH-------HHHHHHHH--BBBBBB--BBBBBBHHHHBBB--BBB-----BBBBBBBB------BBBBBBB--------BBBBBBBBBBB--BBBBBBBBBBBBBBB----HHHHHHH------HHHHHHHHHHHHHH----------HHHHHHHHHHHHHHHHHHHHHH---*

>1ZPV:A|PDBID|CHAIN|SEQUENCE
MKAIITVVGKDKSGIVAGVSGKIAELGLNIDDISQTVLDEYFTMMAVVSSDEKQDFTYLRNEFEAFGQTLNVKINIQSAAIFEAMYNI*
BBBBBBBBBB----HHHHHHHHHHH---BBBBBBBBBB--BBBBBBBBBBBB---HHHHHHHHHHHHHH---BBBBBBHHH-------*

>1ZS7:A|PDBID|CHAIN|SEQUENCE
MARLEARALSKKERRSLLERLKPYYTRIPFSEKADLRLVKARTDSGEYEIITVDGVPCLFEWSDGRIYPTLQCLKAFGVDWLKGVVLVDKGAAIALAKGAHLMIPGVVGVEGSFTRGDVVAALYHETRTPVMVGVAEVDSSALEKLYREKARGRAVRRVHRLGDALWELAQEVGKRLSGS*
----------HHHHHHHHHHHHHH-----------BBBBBBB----BBBBBBB--BBBBBB-----BBB-HHHHHHH------BBBBB-HHHHHHH-----BBHHHBBBBBB------BBBBBB----BBBBBBBB---HHHHHHHHHH----BBBBBBBB---HHHHHHHHHHHHH---*

>1ZSD:B|PDBID|CHAIN|SEQUENCE
IQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM*
-----BBBBBBBB-HHH---BBBBBBBBBBBBB--BBBBBB--BBB----BBBBBBBBBBBB---BBBBB-------BBBBBB---BBB-BBBB--HHH*

>1ZLT:A|PDBID|CHAIN|SEQUENCE
MAVPFVEDWDLVQTLGEGAYGEVQLAVNRVTEEAVAVKIVDMKRAVDCPENIKKEICINKMLNHENVVKFYGHRREGNIQYLFLEYCSGGELFDRIEPDIGMPEPDAQRFFHQLMAGVVYLHGIGITHRDIKPENLLLDERDNLKISDFGLATVFRYNNRERLLNKMCGTLPYVAPELLKRREFHAEPVDVWSCGIVLTAMLAGELPWDQPSDSCQEYSDWKEKKTYLNPWKKIDSAPLALLHKILVENPSARITIPDIKKDRWYNKPLKKGAKRPRVTSGGVSESPSGF*
--HHHHHHBBBBBBBBB-BBBBBBBBBBCCC--BBBBBBBBHHH---HHHHHHHHHHHHH---------BBBBBB---BBBBBBB--BBBBHHHH--CCC---HHHHHHHHHHHHHHHHHHHH-BBB-----HHHBBB-----BBB--HHH-BBBBB-------------HHH--HHHH--BBB-HHHHHHHHHHHHHHHHHH-----BBB-BBBHHHHHHH----BBB-HHH--HHHHHHHHHH----CCC---HHHH---CCCC------------------------*

>1ZXU:A|PDBID|CHAIN|SEQUENCE
MEQPYVYAYPQGSGPSGAPTPQAGGVVVDPKYCAPYPIDMAIVRKMMSLTDGNFVITDVNGNLLFKVKEPVFGLHDKRVLLDGSGTPVVTLREKMVSMHDRWQVFRGGSTDQRDLLYTVKRSSMLQLKTKLDVFLGHNKDEKRCDFRVKGSWLERSCVVYAGESDAIVAQMHRKHTVQSVFLGKDNFSVTVYPNVDYAFIASLVVILDDVNREDRAA*
-----------------------------HHH-----BBBBBB----------BBBBB----BBBBBB-------BBBBBB-----BBBBBB--------BBBBBB-----HHHBBBBBB----------BBBBB---------BBBBBB-CCCC--BBBBCCC--BBBBBBB------------BBBBBB-----HHHHHHHHHHHHHHH------*

>1ZTE:A|PDBID|CHAIN|SEQUENCE
KHSLPDLPYDYGALEPHINAQIMQLHHSKHHAAHVNNLNVTEEKYQEALAKGDVTAQIALQPALKFNGGGHINHSIFWTNLSPNGGGEPKGELLEAIKRDFGSFDKFKEKLTAASVGVQGSGWGWLGFNKERGHLQIAACPNQDPLQGTTGLIPLLGIDVWEHAYYLQYKNVRPDYLKAIWNVINWENVTERYMACKK*
----------CCCCCCC--HHHHHHHHH-HHHHHHHHHHHHHHHHHHHHH---HHHHHH-HHHHHHHHHHHHHHHHHHH-----------HHHHHHHHHHH--HHHHHHHHHHHHH---BBBBBBBBBBCCCCBBBBBBBB----HHHHH--BBBBBBB--HHH-HHHH---HHHHHHHHHHH--HHHHHHHHHH---*

>1ZOH:A|PDBID|CHAIN|SEQUENCE
MSKARVYADVNVLRPKEYWDYEALTVQWGEQDDYEVVRKVGRGKYSEVFEGINVNNNEKCIIKILKPVKKKKIKREIKILQNLCGGPNIVKLLDIVRDQHSKTPSLIFEYVNNTDFKVLYPTLTDYDIRYYIYELLKALDYCHSQGIMHRDVKPHNVMIDHELRKLRLIDWGLAEFYHPGKEYNVRVASRYFKGPELLVDLQDYDYSLDMWSLGCMFAGMIFRKEPFFYGHDNHDQLVKIAKVLGTDGLNVYLNKYRIELDPQLEALVGRHSRKPWLKFMNADNQHLVSPEAIDFLDKLLRYDHQERLTALEAMTHPYFQQVRAAENSRTRA*
----BBB--HHHH--HHHH-HHH-------HHHBBBBBBBBB-BBBBBBBBBBCCC--BBBBBBB----HHHHHHHHHHHHHH--------BBBBBB-CCC--BBBBBB------HHHHHHH--HHHHHHHHHHHHHHHHHHHH---------HHHBBBBCCCCBBBB--HHH----------------HHH--HHHHH-------HHHHHHHHHHHHHHHH--BBBB----HHHHHHHHHHHH-HHHHHHHHHHH-----HHHHHHH-------HHHH--CCCCCC--HHHHHHHHHH----HHH---HHHHHH-HHHHHHHHHHH-----*

>2A15:A|PDBID|CHAIN|SEQUENCE
MTQTTQSPALIASQSSWRCVQAHDREGWLALMADDVVIEDPIGKSVTNPDGSGIKGKEAVGAFFDTHIAANRLTVTCEETFPSSSPDEIAHILVLHSEFDGGFTSEVRGVFTYRVNKAGLITNMRGYWNLDMMTFGNQE*
-------HHHHHHHHHHHHHH---HHHHHH-BBBBBBBB--------------BB-HHHHHHHHHHH------BBBBBBBBB-----BBBBBBBBBBBB---BBBBBBBBBBBBB-----BBBBBBB--HHH-BBB---*

>1ZWX:A|PDBID|CHAIN|SEQUENCE
QASDEYPGNFKITSHNVYLFSRNIYPNWGQMHRADLIAQADYMKNNDVVILNEAFDTSASHRLLNNLREMYPHQTPVIGRSKHGWDKTEGNYSNFALEDGGVAVVSQWPIVEKSQHIFQRGGGADRLSNKGFAYVKIMKNGKPYHIIGTHTQADDSLISKDTSRAIRAEQMQEIQTFIAKKNIPKDEIIFIGGDLNVNYGTDEYHDMLKLLNVSSPANFNGQMATWDPTTNSMLKESYPKAAPEYLDYIFVENGHARPHSWHNKVLHTKSPQWSVKSWFKTYTYQDFSDHYPVVGFTDNN*
----------BBBBBBBBB--CCC-----HHHHHHHHH--HHH---BBBBBBBB--HHHHHHHHHHCCCC---------------BBBB-------------BBBBBB-BBBBBBBB-----HHHHH---BBBBBBBBB--BBBBBBBBB---------HHHHHHHHHHHHHHHHHHHHHH-----BBBBBBBB-------HHHHHHHHHH----------------CCC-HHHHHH---------BBBBBB--------BBBBB-------BBBBB--BBBBB--BBBB--BBBBB---*

>1ZZI:A|PDBID|CHAIN|SEQUENCE
GPIITTQVTIPKDLAGSIIGKGGQRIKQIRHESGASIKIDEPLEGSEDRIITITGTQDQIQNAQYLLQNSVKQYSGKFF*
---BBBBBBBBCCCHHHH--HHHHHHHHHHHHH--BBBB------BBBBBBBBBB-HHHHHHHHHHHHHHHHHHH----*

>1ZZQ:A|PDBID|CHAIN|SEQUENCE
RFLKVKNWETDVVLTDTLHLKSTLETGCTEHICMGSIMLPSQHTRKPEDVRTKDQLFPLAKEFLDQYYSSIKRFGSKAHMDRLEEVNKEIESTSTYQLKDTELIYGAKHAWRNASRCVGRIQWSKLQVFDARDCTTAHGMFNYICNHVKYATNKGNLRSAITIFPQRTDGKHDFRVWNSQLIRYAGYKQPDGSTLGDPANVQFTEICIQQGWKAPRGRFDVLPLLLQANGNDPELFQIPPELVLEVPIRHPKFDWFKDLGLKWYGLPAVSNMLLEIGGLEFSACPFSGWYMGTEIGVRNYCDNSRYNILEEVAKKMDLDMRKTSSLWKDQALVEINIAVLYSFQSDKVTIVDHHSATESFIKHMENEYRCRGGCPADWVWIVPPMSGSITPVFHQEMLNYRLTPSFEYQPDPWNTHVWKG*
--BBBBBCCC--BBBB-HHHH--------BBBB--------BBB--BBB---HHHHHHHHHHHHHHHHHH---BBBHHHHHHHHHHHHHHHHH------HHHHHHHHHHHHH-------HHH----BBBB------HHHHHHHHHHHHHHHHHHH----BBBB----BBBBB-----BBBBB---BBB---BBBBB-HHHHHHHHHHHH--------------BBBB-BBB--BBB---HHH--BBB--------HHHH--BBBB-------BBBB--BBBB---------HHHHH-HHHH-CCCC--HHHHHHH-------HHH-HHHHHHHHHHHHHHHHHHH-------HHHHHHHHHHHHHHHHHHH------HHHH--BBBHHH-HHHH---BBB--BBBBB----HHHH-----*

>1ZP5:A|PDBID|CHAIN|SEQUENCE
MLTPGNPKWERTNLTYRIRNYTPQLSEAEVERAIKDAFELWSVASPLIFTRISQGEADINIAFYQRDHGDNSPFDGPNGILAHAFQPGQGIGGDAHFDAEETWTNTSANYNLFLVAAHEFGHSLGLAHSSDPGALMYPNYAFRETSNYSLPQDDIDGIQAIYG*
-----------BBBBBBB----BBB-HHHHHHHHHHHHHHHH-----BBBB-BBB--BBBBBBB----BBB----BBBB--BBB--BBBCCCC-BBBB-----BBBBBB--HHHHHHHHHHHHH------------BBB-----BBB----HHHHHHHHHHH-*

>1ZSD:A|PDBID|CHAIN|SEQUENCE
GSHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYRESLRNLRGYYNQSEAGSHIIQRMYGCDLGPDGRLLRGHDQSAYDGKDYIALNEDLSSWTAADTAAQITQRKWEAARVAEQLRAYLEGLCVEWLRRYLENGKETLQRADPPKTHVTHHPVSDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDRTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWEP*
--BBBBBBBBBB----BBB-BBBBBBBB--BBBBBBB--BBB--BBB--HHH----HHHHHHHHHHHHHHHHHHHHHHHHHHHH----BBB--BBBBBBBBBB-----BBBBBBBBBB--BBBBBB------BBBBBHHHHHHHHHHHH--HHHHHHHHHH-HHHHHHHHHHHH-HHHH------BBBBBBBB-BBBBBBBBBBBBBBBBB--BBBBBB-----HHHBBB------BBB-BBBBBBBBBB---HHHBBBBBB---BBB-BBB----*

>1YVM:A|PDBID|CHAIN|SEQUENCE
MAISIKTPEDIEKMRVAGRLAAEVLEMIEPYVKPGVSTGELDRICNDYIVNEQHAVSACLGYHGYPKSVCISINEVVCHGIPDDAKLLKDGDIVNIDVTVIKDGFHGDTSKMFIVGKPTIMGERLCRITQESLYLALRMVKPGINLREIGAAIQKFVEAEGFSVVREYCGHGIGQGFHEEPQVLHYDSRETNVVLKPGMTFTIEPMVNAGKKEIRTMKDGWTVKTKDRSLSAQYEHTIVVTDNGCEILTLRKDDTIPAIISHDE*
-------HHHHHHHHHHHHHHHHHHHHHHHH------HHHHHHHHHHHHHH----BBBB--HHH--BBBBBBB--BBB--------------BBBBBBBBBB--BBBBBBBBBB-BBB-HHHHHHHHHHHHHHHHHHHH------HHHHHHHHHHHHHH------BBB-BBB-BBBBBBBBBB----------------BBBB--BBBBB---BBB-BBBB-BBB-----BBB-BBBBBBB--BBBBBB--------BBBB---*

>1Z55:A|PDBID|CHAIN|SEQUENCE
KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL*
----HHHHHHHHHHCCCCCHHH--HHHHHHHHHHHHBBB---BBB-BBB-BBBCCCC--CCCC---BBB----------HHHHHBBB-HHHHHHHHHHHHBBB-HHH-HHHHHHCCC--HHHHCCC---*

>1YLX:A|PDBID|CHAIN|SEQUENCE
MEFAPRSVVIEEFIDTLEPMMEAYGLDQVGIFEEHGEGNRYYVGYTINKDDEMITIHMPFVKNERGELALEKQEWTVRKDGREKKGFHSLQEAMEEVIHS*
-----HHHHHHHHHHHHHHHHHHH----BBBBBBB----BBBBBBBBBB--BBBBBBBBBBB-----BBB----BBBBB--BBBBBB--HHHHHHHHH--";


$string = str_replace('|CHAIN|SEQUENCE
', '*', $string);
$string = str_replace('\n', '*', $string);

$string = trim(preg_replace('/\s+/', ' ', $string));
$string = str_replace(' ', '', $string);

echo $string;

 $i=0;
 $j=1;
 $k=2;
        $protein = explode("*", $string);
         while($protein[$i])
         {
             $query= "INSERT INTO `major`.`protein_aplusb` (`sr`, `id`, `residue`, `che`, `length`) VALUES (NULL, '$protein[$i]', '$protein[$j]', '$protein[$k]', '0')";

             mysql_query($query);
           $i= $i+3;
           $j= $j+3;
           $k= $k+3;
         }
       
      
       
?>
